version: '3'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: workmed
      POSTGRES_REPLICATION_MODE: "master"
      POSTGRES_REPLICATION_USER: "replicator"
      POSTGRES_REPLICATION_PASSWORD: "replicator_password"
    ports:
      - "5432:5432"

  postgres-slave:
    image: postgres:latest
    container_name: postgres-slave
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: workmed
      POSTGRES_REPLICATION_MODE: "slave"
      POSTGRES_REPLICATION_USER: "replicator"
      POSTGRES_REPLICATION_PASSWORD: "replicator_password"
      POSTGRES_MASTER_HOST: postgres-db
    ports:
      - "5433:5433"

  react-app:
    build: .
    image: node:20 
    container_name: react-app
    working_dir: /src/
    depends_on:
      - api
    volumes:
      - ./frontend:/src/
    ports:
      - "3000:3000"
    command: yarn start

  api:
    image: node:latest
    container_name: api
    working_dir: /src/
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: workmed
      DB_USER: postgres
      DB_PASSWORD: docker
    volumes:
      - ./backend:/src/
    ports:
      - "3333:3333"
    depends_on:
      - postgres-db
      - postgres-slave
    command: yarn dev

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api